'use client'

import { useEffect, useMemo, useState } from 'react'
import { createClient } from '../lib/supabase'

const supabase=createClient()
const fmtDate=v=>{if(!v)return '—';const d=new Date(v+'T12:00:00');return d.toLocaleDateString(undefined,{month:'short',day:'numeric',year:'numeric'})}
const fmtStatus=v=>(v||'').replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase())

export default function EventsCenter({back}){
  const[events,setEvents]=useState([]),[search,setSearch]=useState(''),[selected,setSelected]=useState(null),[mode,setMode]=useState('list'),[loading,setLoading]=useState(true),[admin,setAdmin]=useState(false),[notice,setNotice]=useState('')
  async function load(){setLoading(true);const{data:{user}}=await supabase.auth.getUser();const[{data,error},{data:emp}]=await Promise.all([supabase.from('events').select('id,name,event_date,location_text,status,fulfillment,must_ship_by,return_expected,locked').order('event_date',{ascending:true}),user?supabase.from('employees').select('app_access').eq('id',user.id).single():Promise.resolve({data:null})]);if(error)alert(error.message);setEvents(data||[]);setAdmin(emp?.app_access==='administrator');setLoading(false)}
  useEffect(()=>{load()},[])
  function showNotice(message){setNotice(message);window.setTimeout(()=>setNotice(''),2500)}
  const filtered=useMemo(()=>{const q=search.trim().toLowerCase();return events.filter(e=>!q||[e.name,e.event_date,e.location_text,e.status,e.fulfillment].filter(Boolean).some(v=>String(v).toLowerCase().includes(q)))},[events,search])
  const today=new Date().toISOString().slice(0,10),pastStatuses=new Set(['returned','closed','cancelled'])
  const upcoming=filtered.filter(e=>!pastStatuses.has(e.status)&&(e.event_date>=today||['draft','confirmed','ready_to_pack','packing','packed','checked_out','shipped'].includes(e.status))).sort((a,b)=>(a.fulfillment==='ship'&&a.must_ship_by?a.must_ship_by:a.event_date).localeCompare(b.fulfillment==='ship'&&b.must_ship_by?b.must_ship_by:b.event_date))
  const past=filtered.filter(e=>!upcoming.some(u=>u.id===e.id)).sort((a,b)=>b.event_date.localeCompare(a.event_date))
  if(mode==='create')return <CreateEvent cancel={()=>setMode('list')} created={async()=>{await load();setMode('list')}}/>
  if(mode==='repeat')return <><button className="back" onClick={()=>setMode('list')}>‹ Back</button><h1>Repeat Previous Event</h1><div className="eventEmptyCard"><b>Repeat Previous Event</b><p>Selecting what to copy will be added next.</p></div></>
  if(selected)return <EventPage event={selected} admin={admin} close={async message=>{setSelected(null);await load();if(message)showNotice(message)}}/>
  return <>{notice&&<div className="eventNotice" role="status">{notice}</div>}<button className="back" onClick={back}>‹ Back</button><h1>Events</h1><div className="eventSearch"><span>⌕</span><input type="search" placeholder="Search events" value={search} onChange={e=>setSearch(e.target.value)}/>{search&&<button onClick={()=>setSearch('')}>×</button>}</div><div className="eventActions"><button className="primary" onClick={()=>setMode('create')}>+ Create Event</button><button className="secondaryAction" onClick={()=>setMode('repeat')}>↻ Repeat Previous Event</button></div>{loading?<p className="returnEmpty">Loading events…</p>:<><EventGroup title="Upcoming Events" rows={upcoming} empty="No upcoming events yet." open={setSelected}/><EventGroup title="Past Events" rows={past} empty="No past events yet." open={setSelected}/></>}</>
}

function CreateEvent({cancel,created}){
  const[name,setName]=useState(''),[date,setDate]=useState(''),[location,setLocation]=useState(''),[fulfillment,setFulfillment]=useState('local'),[status,setStatus]=useState('confirmed'),[employees,setEmployees]=useState([]),[selectedEmployees,setSelectedEmployees]=useState([]),[products,setProducts]=useState([]),[productSearch,setProductSearch]=useState(''),[packing,setPacking]=useState([]),[taskText,setTaskText]=useState(''),[taskAssignee,setTaskAssignee]=useState(''),[tasks,setTasks]=useState([]),[thirdParty,setThirdParty]=useState([]),[showThirdParty,setShowThirdParty]=useState(false),[shipTo,setShipTo]=useState(''),[shippingAddress,setShippingAddress]=useState(''),[mustShipBy,setMustShipBy]=useState(''),[mustArriveBy,setMustArriveBy]=useState(''),[returnExpected,setReturnExpected]=useState(true),[busy,setBusy]=useState(false)
  useEffect(()=>{(async()=>{const[{data:e,error:ee},{data:p,error:pe}]=await Promise.all([supabase.from('employees').select('id,name,email,job_title').eq('status','active').order('name'),supabase.from('products').select('id,name,color,size,keywords,program').eq('active',true).order('name')]);if(ee||pe)return alert((ee||pe).message);setEmployees(e||[]);setProducts(p||[])})()},[])
  const pq=productSearch.trim().toLowerCase(),suggestions=pq?products.filter(p=>!packing.some(x=>x.product_id===p.id)&&[p.name,p.color,p.size,p.keywords,p.program].filter(Boolean).some(v=>String(v).toLowerCase().includes(pq))).slice(0,8):[]
  function toggleEmployee(id){setSelectedEmployees(v=>v.includes(id)?v.filter(x=>x!==id):[...v,id])}
  function addProduct(p){setPacking(v=>[...v,{product_id:p.id,name:p.name,color:p.color||'',size:p.size||'',qty_needed:1}]);setProductSearch('')}
  function changePack(id,n){setPacking(v=>v.map(x=>x.product_id===id?{...x,qty_needed:n===''?'':Math.max(1,Number(n)||1)}:x))}
  function finishPackQty(id){setPacking(v=>v.map(x=>x.product_id===id?{...x,qty_needed:x.qty_needed===''?1:x.qty_needed}:x))}
  function addTask(){const t=taskText.trim();if(!t)return;setTasks(v=>[...v,{key:crypto.randomUUID(),task_text:t,assigned_employee_id:taskAssignee||null}]);setTaskText('');setTaskAssignee('')}
  function addThirdParty(){setThirdParty(v=>[...v,{key:crypto.randomUUID(),third_party_name:'',staffing_company:'',staff_count:1}]);setShowThirdParty(true)}
  function updateThird(k,field,value){setThirdParty(v=>v.map(x=>x.key===k?{...x,[field]:value}:x))}
  async function submit(e){e.preventDefault();if(!name.trim()||!date)return alert('Event Name and Date are required.');if(packing.some(x=>x.qty_needed===''||Number(x.qty_needed)<1))return alert('Packing quantities must be at least 1.');setBusy(true);const{data:{user}}=await supabase.auth.getUser();const eventRow={name:name.trim(),event_date:date,location_text:location.trim()||null,fulfillment,status,return_expected:fulfillment==='ship'?returnExpected:true,ship_to:fulfillment==='ship'?(shipTo.trim()||null):null,shipping_address:fulfillment==='ship'?(shippingAddress.trim()||null):null,must_ship_by:fulfillment==='ship'?(mustShipBy||null):null,must_arrive_by:fulfillment==='ship'?(mustArriveBy||null):null,confirmed_at:status==='confirmed'?new Date().toISOString():null,created_by:user?.id||null,updated_by:user?.id||null};const{data:event,error}=await supabase.from('events').insert(eventRow).select('id').single();if(error){setBusy(false);return alert(error.message)}
    const staff=[...selectedEmployees.map(employee_id=>({event_id:event.id,employee_id})),...thirdParty.filter(x=>x.third_party_name.trim()||x.staffing_company.trim()).map(x=>({event_id:event.id,third_party_name:x.third_party_name.trim()||null,staffing_company:x.staffing_company.trim()||null,staff_count:Math.max(1,Number(x.staff_count)||1)}))]
    const itemRows=packing.map(x=>({event_id:event.id,product_id:x.product_id,qty_needed:Number(x.qty_needed),qty_packed:0,packed:false})),taskRows=tasks.map(x=>({event_id:event.id,task_text:x.task_text,assigned_employee_id:x.assigned_employee_id,completed:false}))
    for(const [table,rows] of [['event_staff',staff],['event_items',itemRows],['event_tasks',taskRows]]){if(rows.length){const{error:er}=await supabase.from(table).insert(rows);if(er){setBusy(false);return alert(`Event created, but ${table.replaceAll('_',' ')} could not be saved: ${er.message}`)}}}
    setBusy(false);alert('Event Created ✓');created()}
  return <><button className="back" onClick={cancel}>‹ Events</button><h1>Create Event</h1><form className="createEventForm" onSubmit={submit}>
    <section className="createEventCard"><label>Event Name<input required value={name} onChange={e=>setName(e.target.value)} placeholder="Event name"/></label><div className="createEventGrid"><label>Date<input required type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><label>Location<input value={location} onChange={e=>setLocation(e.target.value)} placeholder="Event location"/></label></div></section>
    <section className="createEventCard"><h2>Employees Working Event</h2>{employees.length?<div className="employeePicker">{employees.map(e=><label className="employeeChoice" key={e.id}><input type="checkbox" checked={selectedEmployees.includes(e.id)} onChange={()=>toggleEmployee(e.id)}/><span><b>{e.name}</b>{e.job_title&&<small>{e.job_title}</small>}</span></label>)}</div>:<p className="returnEmpty">No active employees found.</p>}<button type="button" className="addTextButton" onClick={addThirdParty}>+ Third-Party Staff</button>{showThirdParty&&thirdParty.map(x=><div className="thirdPartyRow" key={x.key}><input placeholder="Name (optional)" value={x.third_party_name} onChange={e=>updateThird(x.key,'third_party_name',e.target.value)}/><input placeholder="Staffing company / role" value={x.staffing_company} onChange={e=>updateThird(x.key,'staffing_company',e.target.value)}/><input type="number" min="1" value={x.staff_count} onChange={e=>updateThird(x.key,'staff_count',e.target.value)}/><button type="button" onClick={()=>setThirdParty(v=>v.filter(y=>y.key!==x.key))}>Remove</button></div>)}</section>
    <section className="createEventCard"><h2>Event Fulfillment</h2><div className="segmented"><button type="button" className={fulfillment==='local'?'active':''} onClick={()=>setFulfillment('local')}>Local</button><button type="button" className={fulfillment==='ship'?'active':''} onClick={()=>setFulfillment('ship')}>Ship</button></div>{fulfillment==='ship'&&<div className="shippingFields"><label>Ship To<input value={shipTo} onChange={e=>setShipTo(e.target.value)}/></label><label>Shipping Address<textarea value={shippingAddress} onChange={e=>setShippingAddress(e.target.value)}/></label><div className="createEventGrid"><label>Must Ship By<input type="date" value={mustShipBy} onChange={e=>setMustShipBy(e.target.value)}/></label><label>Must Arrive By<input type="date" value={mustArriveBy} onChange={e=>setMustArriveBy(e.target.value)}/></label></div><label className="employeeChoice"><input type="checkbox" checked={returnExpected} onChange={e=>setReturnExpected(e.target.checked)}/><span><b>Return Expected</b></span></label></div>}<label className="statusField">Status<select value={status} onChange={e=>setStatus(e.target.value)}><option value="confirmed">Confirmed</option><option value="draft">Draft</option></select></label></section>
    <section className="createEventCard"><h2>Packing List</h2><div className="productTypeahead"><input value={productSearch} onChange={e=>setProductSearch(e.target.value)} placeholder="Type a product name or keyword…"/>{suggestions.length>0&&<div className="productSuggestions">{suggestions.map(p=><button type="button" key={p.id} onClick={()=>addProduct(p)}><b>{p.name}</b><small>{[p.color,p.size].filter(Boolean).join(' · ')}</small></button>)}</div>}</div>{packing.length?<div className="builderRows">{packing.map(x=><div className="builderRow" key={x.product_id}><span><b>{x.name}</b>{(x.color||x.size)&&<small>{[x.color,x.size].filter(Boolean).join(' · ')}</small>}</span><div className="miniQty"><button type="button" onClick={()=>changePack(x.product_id,Math.max(1,Number(x.qty_needed||1)-1))}>−</button><input inputMode="numeric" value={x.qty_needed} onChange={e=>changePack(x.product_id,e.target.value)} onBlur={()=>finishPackQty(x.product_id)}/><button type="button" onClick={()=>changePack(x.product_id,Number(x.qty_needed||0)+1)}>+</button></div><button type="button" className="removeItem" onClick={()=>setPacking(v=>v.filter(y=>y.product_id!==x.product_id))}>Remove</button></div>)}</div>:<p className="returnEmpty">No packing items yet.</p>}<div className="builderSecondaryActions"><button type="button">+ Kit</button><button type="button">+ Batch</button></div></section>
    <section className="createEventCard"><h2>Tasks <span className="optionalText">Optional</span></h2><div className="taskEntry"><input value={taskText} onChange={e=>setTaskText(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'){e.preventDefault();addTask()}}} placeholder="Type a task…"/><select value={taskAssignee} onChange={e=>setTaskAssignee(e.target.value)}><option value="">Unassigned</option>{employees.filter(e=>selectedEmployees.includes(e.id)).map(e=><option key={e.id} value={e.id}>{e.name}</option>)}</select><button type="button" onClick={addTask}>+ Add</button></div>{tasks.length>0&&<div className="builderRows">{tasks.map(t=><div className="builderRow taskBuilderRow" key={t.key}><span><b>{t.task_text}</b><small>{t.assigned_employee_id?(employees.find(e=>e.id===t.assigned_employee_id)?.name||'Assigned'):'Unassigned'}</small></span><button type="button" className="removeItem" onClick={()=>setTasks(v=>v.filter(x=>x.key!==t.key))}>Remove</button></div>)}</div>}</section>
    <button className="primary createEventSubmit" disabled={busy}>{busy?'Creating…':'Create Event'}</button>
  </form></>}

function EventGroup({title,rows,empty,open}){return <section className="eventGroup"><h2>{title}</h2>{rows.length?<div className="eventCards">{rows.map(e=><button className="eventCard" key={e.id} onClick={()=>open(e)}><span className="eventDate">{fmtDate(e.event_date)}</span><span className="eventCardMain"><b>{e.name}</b><small>{fmtStatus(e.status)}{e.fulfillment==='ship'?' · Ship':''}</small></span><span className="eventChevron">›</span></button>)}</div>:<p className="returnEmpty">{empty}</p>}</section>}

function EventPage({event,admin,close}){
  const[items,setItems]=useState([]),[tasks,setTasks]=useState([]),[notes,setNotes]=useState([]),[noteText,setNoteText]=useState(''),[busy,setBusy]=useState(false),[menu,setMenu]=useState(false),[adjust,setAdjust]=useState(null),[adjustQty,setAdjustQty]=useState(''),[finding,setFinding]=useState(null),[findLocations,setFindLocations]=useState([]),[findLoading,setFindLoading]=useState(false)
  async function load(){const[{data:i},{data:t},{data:n}]=await Promise.all([supabase.from('event_items').select('id,product_id,qty_needed,qty_packed,packed,products(name)').eq('event_id',event.id),supabase.from('event_tasks').select('*,employees!event_tasks_assigned_employee_id_fkey(name)').eq('event_id',event.id),supabase.from('event_notes').select('*').eq('event_id',event.id)]);setItems(i||[]);setTasks(t||[]);setNotes(n||[])}
  useEffect(()=>{load()},[event.id])
  async function pack(i,qty=i.qty_needed){setBusy(true);const{error}=await supabase.rpc('pack_event_item',{p_event_item_id:i.id,p_qty_packed:Number(qty)});setBusy(false);if(error)return alert(error.message);setAdjust(null);await load()}
  function openAdjust(i){setAdjust(i);setAdjustQty(String(i.packed?i.qty_packed:i.qty_needed))}
  function changeAdjust(n){if(n==='')return setAdjustQty('');setAdjustQty(String(Math.max(0,Number(n)||0)))}
  async function saveAdjust(){if(adjustQty===''||Number(adjustQty)<0)return alert('Packed quantity must be 0 or more.');await pack(adjust,adjustQty)}
  async function openFind(i){setFinding(i);setFindLocations([]);setFindLoading(true);const{data,error}=await supabase.from('stock').select('on_hand,locations(name)').eq('product_id',i.product_id).gt('on_hand',0).order('on_hand',{ascending:false});setFindLoading(false);if(error)return alert(error.message);setFindLocations(data||[])}
  async function toggleTask(t){setBusy(true);const next=!t.completed;const{data:{user}}=await supabase.auth.getUser();const{error}=await supabase.from('event_tasks').update({completed:next,completed_by:next?(user?.id||null):null,completed_at:next?new Date().toISOString():null}).eq('id',t.id);setBusy(false);if(error)return alert(error.message);await load()}
  async function addNote(){const note=noteText.trim();if(!note)return;setBusy(true);const{data:{user}}=await supabase.auth.getUser();if(!user){setBusy(false);return alert('Please sign in again.')}const{error}=await supabase.from('event_notes').insert({event_id:event.id,note,created_by:user.id});setBusy(false);if(error)return alert(error.message);setNoteText('');await load()}
  async function move(){setBusy(true);const fn=event.fulfillment==='ship'?'mark_event_shipped':'mark_event_checked_out';const{error}=await supabase.rpc(fn,{p_event_id:event.id});setBusy(false);if(error)return alert(error.message);alert(event.fulfillment==='ship'?'Marked shipped':'Event checked out');close()}
  async function cancelEvent(){setMenu(false);if(!window.confirm(`Cancel “${event.name}”?\n\nThis will release its inventory reservations and keep the event in history as Cancelled.`))return;setBusy(true);const{error}=await supabase.rpc('cancel_event',{p_event_id:event.id});setBusy(false);if(error)return alert(error.message);close('Event cancelled ✓')}
  async function deleteEvent(){setMenu(false);if(!window.confirm(`Delete this event?\n\nThis permanently deletes “${event.name}” and releases any inventory reservations. This cannot be undone.`))return;setBusy(true);const{error}=await supabase.rpc('delete_event',{p_event_id:event.id});setBusy(false);if(error)return alert(error.message);close('Event deleted ✓')}
  const canDelete=['draft','confirmed','ready_to_pack'].includes(event.status)&&!event.locked,canCancel=!['returned','closed','cancelled'].includes(event.status)
  return <><button className="back" onClick={close}>‹ Events</button><div className="eventPageTop"><div className="eventPageHeader"><span className="eventDate">{fmtDate(event.event_date)}</span><h1>{event.name}</h1><span className="eventStatusBadge">{fmtStatus(event.status)}</span></div>{admin&&<div className="eventOverflow"><button className="eventOverflowButton" aria-label="Event options" onClick={()=>setMenu(!menu)}>•••</button>{menu&&<div className="eventOverflowMenu">{canCancel&&<button onClick={cancelEvent}>Cancel Event</button>}{canDelete&&<button className="danger" onClick={deleteEvent}>Delete Event</button>}{!canCancel&&!canDelete&&<span>No event actions available</span>}</div>}</div>}</div>
  <details className="eventDetailSection" open><summary>Packing List <span>{items.length}</span></summary><div className="eventDetailBody">{items.length?items.map(i=><div className={`pack packingToolRow${i.packed?' packedRow':''}`} key={i.id}><button className={`packingCheck${i.packed?' checked':''}`} aria-label={i.packed?`${i.products?.name||'Item'} packed`:`Mark ${i.products?.name||'item'} packed`} disabled={busy||i.packed} onClick={()=>pack(i)}>{i.packed?'✓':''}</button><span className="packingProduct"><b>{i.products?.name||'—'}</b><small>Needed: {i.qty_needed}{i.packed&&Number(i.qty_packed)!==Number(i.qty_needed)?` · Packed: ${i.qty_packed}`:''}</small></span><div className="packingActions"><button disabled={busy} onClick={()=>openAdjust(i)}>Adjust Qty</button><button disabled={busy} onClick={()=>openFind(i)}>⌕ Find</button></div></div>):<p className="returnEmpty">No packing items yet.</p>}</div></details>
  <details className="eventDetailSection"><summary>Tasks <span>{tasks.length&&tasks.every(t=>t.completed)?'✓':tasks.filter(t=>!t.completed).length}</span></summary><div className="eventDetailBody">{tasks.length?tasks.map(t=><div className={`eventTaskRow${t.completed?' completed':''}`} key={t.id}><button className={`taskCheck${t.completed?' checked':''}`} aria-label={t.completed?`Mark ${t.task_text} incomplete`:`Mark ${t.task_text} complete`} disabled={busy} onClick={()=>toggleTask(t)}>{t.completed?'✓':''}</button><span className="eventTaskText"><b>{t.task_text}</b><small>{t.employees?.name?`Assigned to ${t.employees.name}`:t.assigned_third_party_name?`Assigned to ${t.assigned_third_party_name}`:'Unassigned'}</small></span></div>):<p className="returnEmpty">No tasks yet.</p>}</div></details><details className="eventDetailSection"><summary>Notes <span>{notes.length}</span></summary><div className="eventDetailBody">{event.status!=='closed'?<div className="eventNoteEntry"><textarea value={noteText} onChange={e=>setNoteText(e.target.value)} placeholder="Add a note…" rows="3"/><button className="secondaryAction" disabled={busy||!noteText.trim()} onClick={addNote}>{busy?'Saving…':'Add Note'}</button></div>:<p className="eventReadOnlyNote">Event closed · Notes are read-only</p>}{notes.length?<div className="eventNotesList">{notes.map(n=><div className="eventNoteRow" key={n.id}><p>{n.note_text||n.note||n.content||'Note'}</p>{n.created_at&&<small>{new Date(n.created_at).toLocaleString(undefined,{month:'short',day:'numeric',hour:'numeric',minute:'2-digit'})}</small>}</div>)}</div>:<p className="returnEmpty">No notes yet.</p>}</div></details>{['packing','packed'].includes(event.status)&&<button className="primary eventMoveButton" disabled={busy} onClick={move}>{event.fulfillment==='ship'?'Mark as Shipped':'Check Out Event'}</button>}
  {adjust&&<div className="modalBackdrop" onClick={()=>setAdjust(null)}><div className="qtyModal" onClick={e=>e.stopPropagation()}><h2>Adjust Qty</h2><p><b>{adjust.products?.name||'Product'}</b></p><small>Needed {adjust.qty_needed}</small><div className="qtyPicker"><button onClick={()=>changeAdjust(Math.max(0,Number(adjustQty||0)-1))}>−</button><input inputMode="numeric" value={adjustQty} onChange={e=>changeAdjust(e.target.value)}/><button onClick={()=>changeAdjust(Number(adjustQty||0)+1)}>+</button></div><button className="primary" disabled={busy} onClick={saveAdjust}>{busy?'Saving…':'Save Packed Qty'}</button><button className="cancelModal" onClick={()=>setAdjust(null)}>Cancel</button></div></div>}
  {finding&&<div className="modalBackdrop" onClick={()=>setFinding(null)}><div className="qtyModal findModal" onClick={e=>e.stopPropagation()}><h2>{finding.products?.name||'Find Product'}</h2><p className="findLabel">Location</p>{findLoading?<p>Loading…</p>:findLocations.length?<div className="findLocations">{findLocations.map((s,idx)=><div className="findLocation" key={idx}><b>{s.locations?.name||'Unknown location'}</b><small>{s.on_hand} on hand</small></div>)}</div>:<p className="returnEmpty">No stocked location found.</p>}<button className="cancelModal" onClick={()=>setFinding(null)}>Close</button></div></div>}</>}
