'use client'

import { useEffect, useState } from 'react'
import { createClient } from '../lib/supabase'

const supabase = createClient()

function Login({ onLogin }) {
  const [email,setEmail]=useState('')
  const [password,setPassword]=useState('')
  const [mode,setMode]=useState('login')
  const [message,setMessage]=useState('')
  const submit=async(e)=>{e.preventDefault();setMessage('');const result=mode==='signup'?await supabase.auth.signUp({email,password,options:{data:{name:email.split('@')[0]}}}):await supabase.auth.signInWithPassword({email,password});if(result.error)return setMessage(result.error.message);if(result.data.session)onLogin(result.data.session);else setMessage('Account created. Check your email if confirmation is required, then sign in.')}
  return <main className="login"><div className="brand">LA PULGA</div><div className="panel"><h1>{mode==='login'?'Sign In':'Create First Account'}</h1><form onSubmit={submit}><label>Email<input type="email" required value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Password<input type="password" minLength="6" required value={password} onChange={e=>setPassword(e.target.value)}/></label><button className="primary">{mode==='login'?'Sign In':'Create Account'}</button></form>{message&&<p className="message">{message}</p>}<button className="link" onClick={()=>setMode(mode==='login'?'signup':'login')}>{mode==='login'?'Set up the first La Pulga account':'Back to Sign In'}</button></div></main>
}

export default function Home(){
 const [session,setSession]=useState(null),[employee,setEmployee]=useState(null),[events,setEvents]=useState([]),[low,setLow]=useState(0),[view,setView]=useState('home'),[loading,setLoading]=useState(true)
 async function load(s){if(!s){setLoading(false);return}const [{data:emp},{data:ev},{data:inv}]=await Promise.all([supabase.from('employees').select('*').eq('id',s.user.id).single(),supabase.from('events').select('id,name,event_date,status,fulfillment,must_ship_by').not('status','eq','closed').order('event_date'),supabase.from('inventory_available').select('product_id,available_qty,minimum_stock,reusable')]);setEmployee(emp);setEvents(ev||[]);setLow((inv||[]).filter(x=>x.minimum_stock>0&&x.available_qty<=x.minimum_stock).length);setLoading(false)}
 useEffect(()=>{supabase.auth.getSession().then(({data})=>{setSession(data.session);load(data.session)});const {data:{subscription}}=supabase.auth.onAuthStateChange((_e,s)=>{setSession(s);load(s)});return()=>subscription.unsubscribe()},[])
 if(loading)return <main className="center">Loading LA PULGA…</main>
 if(!session)return <Login onLogin={s=>{setSession(s);load(s)}}/>
 const admin=employee?.app_access==='administrator'
 return <main><header><div><b>LA PULGA</b></div><button className="profileButton" aria-label="Profile" onClick={()=>setView('profile')}>👤</button></header><div className="content">{view==='home'&&<><h1>Home</h1>{admin&&<div className="stats"><button onClick={()=>setView('events')}><strong>{events.length}</strong><span>Upcoming Events</span></button><button><strong>0</strong><span>Needs Attention</span></button><button><strong>{low}</strong><span>Low Stock</span></button></div>}<div className="menu"><button onClick={()=>setView('events')}>Events <span>›</span></button><button onClick={()=>setView('checkout')}>General Checkout <span>›</span></button><button onClick={()=>setView('returns')}>Returns <span>›</span></button><button onClick={()=>setView('inventory')}>Inventory <span>›</span></button></div></>}{view==='profile'&&<Profile employee={employee} admin={admin} back={()=>setView('home')} onLogout={async()=>{await supabase.auth.signOut();setSession(null)}}/>}{!['home','profile'].includes(view)&&<Section view={view} events={events} admin={admin} back={()=>setView('home')}/>}</div></main>
}

function Profile({employee,admin,back,onLogout}){return <><button className="back" onClick={back}>‹ Back</button><h1>Profile</h1><div className="profileCard"><div><span>Name</span><b>{employee?.name||'—'}</b></div><div><span>Job Title</span><b>{employee?.job_title||'—'}</b></div></div>{admin&&<button className="menuButton" disabled>Manage Employees <span>›</span></button>}<button className="logoutButton" onClick={onLogout}>Log Out</button></>}

function Section({view,events,admin,back}){
 const [rows,setRows]=useState([]),[busy,setBusy]=useState(false),[selected,setSelected]=useState(null),[purpose,setPurpose]=useState(''),[search,setSearch]=useState('')
 useEffect(()=>{(async()=>{if(view==='inventory'){const {data,error}=await supabase.from('stock').select('id,on_hand,product_id,location_id,products(id,name,color,size,keywords,program,category_id,categories(name)),locations(name)').order('id');if(error){alert(error.message);setRows([]);return}const {data:available}=await supabase.from('inventory_available').select('product_id,available_qty');const availableMap=Object.fromEntries((available||[]).map(x=>[x.product_id,x.available_qty]));setRows((data||[]).map(r=>({...r,available_qty:availableMap[r.product_id]??r.on_hand})).sort((a,b)=>(a.products?.name||'').localeCompare(b.products?.name||'')))}else if(view==='checkout'){const {data}=await supabase.from('inventory_available').select('*').order('name');setRows(data||[])}else if(view==='returns'){const {data}=await supabase.from('general_checkouts').select('*').in('status',['out','pending_count']).order('checked_out_at',{ascending:false});setRows(data||[])}})()},[view])
 async function checkout(){if(!selected||!purpose)return;setBusy(true);const {error}=await supabase.rpc('create_general_checkout',{p_purpose:purpose,p_items:[{product_id:selected.product_id,quantity:1}]});setBusy(false);if(error)alert(error.message);else{alert('Checkout complete');back()}}
 const q=search.trim().toLowerCase();const inventoryRows=view==='inventory'?rows.filter(r=>{if(!q)return true;const p=r.products||{};return [p.name,r.locations?.name,p.categories?.name,p.keywords,p.color,p.size,p.program].filter(Boolean).some(v=>String(v).toLowerCase().includes(q))}):[]
 return <><button className="back" onClick={back}>‹ Back</button><h1>{view==='checkout'?'General Checkout':view[0].toUpperCase()+view.slice(1)}</h1>{view==='events'&&<div className="list">{events.length?events.map(e=><EventRow key={e.id} event={e}/>):<p>No upcoming events yet.</p>}</div>}{view==='inventory'&&<><div className="inventorySearch"><span>⌕</span><input type="search" placeholder="Search inventory" value={search} onChange={e=>setSearch(e.target.value)}/>{search&&<button onClick={()=>setSearch('')} aria-label="Clear search">×</button>}</div><div className="inventoryCount">{inventoryRows.length} {inventoryRows.length===1?'stock row':'stock rows'}</div><div className="inventoryTableWrap"><div className="inventoryTable"><div className="inventoryTr inventoryHead"><span className="productCell">Product</span><span>Location</span><span>Color</span><span>Size</span><span className="qtyCell">Qty</span></div>{inventoryRows.map(r=><div className="inventoryTr" key={r.id}><span className="productCell">{r.products?.name||'—'}</span><span>{r.locations?.name||'—'}</span><span>{r.products?.color||'—'}</span><span>{r.products?.size||'—'}</span><b className="qtyCell">{r.on_hand}</b></div>)}</div></div>{inventoryRows.length===0&&<p className="emptyState">No inventory matches “{search}”.</p>}</>}{view==='checkout'&&<><p>Select an item to check out.</p><div className="list">{rows.filter(r=>r.available_qty>0).map(r=><button className={'row '+(selected?.product_id===r.product_id?'selected':'')} key={r.product_id} onClick={()=>setSelected(r)}><span>{r.name}</span><b>{r.available_qty} available</b></button>)}</div>{selected&&<div className="checkoutbar"><input placeholder="Purpose" value={purpose} onChange={e=>setPurpose(e.target.value)}/><button className="primary" disabled={busy||!purpose} onClick={checkout}>{busy?'Working…':'Checkout 1'}</button></div>}</>}{view==='returns'&&<div className="list">{rows.length?rows.map(r=><ReturnRow key={r.id} checkout={r}/>):<p>No general checkouts are currently out.</p>}</div>}</>
}

function EventRow({event}){const [open,setOpen]=useState(false),[items,setItems]=useState([]);async function toggle(){if(!open){const {data}=await supabase.from('event_items').select('id,qty_needed,qty_packed,packed,products(name)').eq('event_id',event.id);setItems(data||[])}setOpen(!open)}async function pack(i){const {error}=await supabase.rpc('pack_event_item',{p_event_item_id:i.id,p_qty_packed:i.qty_needed});if(error)return alert(error.message);setItems(items.map(x=>x.id===i.id?{...x,packed:true,qty_packed:x.qty_needed}:x))}async function move(){const fn=event.fulfillment==='ship'?'mark_event_shipped':'mark_event_checked_out';const {error}=await supabase.rpc(fn,{p_event_id:event.id});if(error)alert(error.message);else alert(event.fulfillment==='ship'?'Marked shipped':'Checked out')}return <div className="card"><button className="row" onClick={toggle}><span><b>{event.name}</b><small>{event.event_date} · {event.status.replaceAll('_',' ')}</small></span><span>›</span></button>{open&&<div className="inside">{items.map(i=><div className="pack" key={i.id}><span>{i.products?.name}<small>Need {i.qty_needed}{i.packed?` · Packed ${i.qty_packed}`:''}</small></span><button disabled={i.packed} onClick={()=>pack(i)}>{i.packed?'✓':'Pack'}</button></div>)}{['packing','packed'].includes(event.status)&&<button className="primary" onClick={move}>{event.fulfillment==='ship'?'Mark as Shipped':'Check Out Event'}</button>}</div>}</div>}

function ReturnRow({checkout}){const [busy,setBusy]=useState(false);async function pending(){setBusy(true);const {error}=await supabase.rpc('record_pending_return',{p_source_type:'general_checkout',p_source_id:checkout.id});setBusy(false);if(error)alert(error.message);else alert('Returned. Inventory is pending count verification.')}return <div className="card"><div className="row"><span><b>General Checkout</b><small>{checkout.purpose}</small></span><button disabled={busy||checkout.status==='pending_count'} onClick={pending}>{checkout.status==='pending_count'?'Pending Count':'Return Without Verifying'}</button></div></div>}
