'use client'
import {useEffect,useState} from 'react'
import {useRouter} from 'next/navigation'
import {createClient} from '../../../lib/supabase'
const supabase=createClient()
const blank={first_name:'',last_name:'',email:'',job_title:'',app_access:'employee',status:'active'}
export default function EmployeesPage(){
 const router=useRouter(),[employees,setEmployees]=useState([]),[loading,setLoading]=useState(true),[adding,setAdding]=useState(false),[editing,setEditing]=useState(null),[form,setForm]=useState(blank),[busy,setBusy]=useState(false)
 async function load(){const{data:{user}}=await supabase.auth.getUser();if(!user){router.replace('/');return}const{data:me}=await supabase.from('employees').select('app_access,status').eq('id',user.id).single();if(me?.app_access!=='administrator'||me?.status!=='active'){router.replace('/profile');return}const{data,error}=await supabase.from('employees').select('id,name,job_title,app_access,status,email,setup_completed_at').order('name');if(error){alert(error.message);return}setEmployees(data||[]);setLoading(false)}
 useEffect(()=>{load()},[])
 async function add(e){e.preventDefault();if(!form.first_name.trim()||!form.last_name.trim()||!form.email.trim())return alert('First Name, Last Name, and Email are required.');setBusy(true);const{error}=await supabase.functions.invoke('admin-add-employee',{body:form});setBusy(false);if(error)return alert(error.message||'Unable to add employee.');setForm(blank);setAdding(false);await load();alert('Employee added. An invitation email has been sent.')}
 async function resend(employee){if(employee.setup_completed_at)return alert('This employee has already completed account setup. Use Forgot Password instead.');setBusy(true);const{data,error}=await supabase.functions.invoke('admin-resend-employee-invite',{body:{employee_id:employee.id}});setBusy(false);if(error)return alert(error.message||'Unable to resend invitation.');alert('A fresh account setup email has been sent to '+employee.email+'.')}
 async function saveEdit(e){e.preventDefault();if(!form.first_name.trim()||!form.last_name.trim())return alert('First Name and Last Name are required.');setBusy(true);const{error}=await supabase.functions.invoke('admin-update-employee',{body:{employee_id:editing.id,first_name:form.first_name,last_name:form.last_name,job_title:form.job_title,app_access:form.app_access,status:form.status}});setBusy(false);if(error)return alert(error.message||'Unable to update employee.');setEditing(null);setForm(blank);await load();alert('Employee updated.')}
 function editEmployee(e){const parts=(e.name||'').trim().split(/\\s+/);setForm({first_name:parts.shift()||'',last_name:parts.join(' '),email:e.email||'',job_title:e.job_title||'',app_access:e.app_access||'employee',status:e.status||'active'});setEditing(e);window.scrollTo(0,0)}
 const field=(k,label,type='text')=><label>{label}<input type={type} required={k!=='job_title'} value={form[k]} onChange={e=>setForm({...form,[k]:e.target.value})}/></label>
 if(loading)return <main className="center">Loading Employees…</main>
 if(editing)return <main><header><div><b onClick={()=>router.push('/')}>LA PULGA</b></div><button className="profileButton" onClick={()=>router.push('/profile')}>👤</button></header><div className="content"><button className="back" onClick={()=>setEditing(null)}>‹ Employees</button><h1>Edit Employee</h1><form className="employeeForm" onSubmit={saveEdit}>{field('first_name','First Name')}{field('last_name','Last Name')}<label>Email<input type="email" value={form.email} disabled/></label>{field('job_title','Job Title')}<label>App Access<select value={form.app_access} onChange={e=>setForm({...form,app_access:e.target.value})}><option value="employee">Employee</option><option value="administrator">Administrator</option></select></label><label>Status<select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option value="active">Active</option><option value="inactive">Inactive</option></select></label><button className="primary" disabled={busy}>{busy?'Saving…':'Save Employee'}</button></form></div><Style/></main>
 if(adding)return <main><header><div><b onClick={()=>router.push('/')}>LA PULGA</b></div><button className="profileButton" onClick={()=>router.push('/profile')}>👤</button></header><div className="content"><button className="back" onClick={()=>setAdding(false)}>‹ Employees</button><h1>Add Employee</h1><form className="employeeForm" onSubmit={add}>{field('first_name','First Name')}{field('last_name','Last Name')}{field('email','Email','email')}{field('job_title','Job Title')}<label>App Access<select value={form.app_access} onChange={e=>setForm({...form,app_access:e.target.value})}><option value="employee">Employee</option><option value="administrator">Administrator</option></select></label><label>Status<select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option value="active">Active</option><option value="inactive">Inactive</option></select></label><button className="primary" disabled={busy}>{busy?'Adding…':'Add Employee'}</button></form></div><Style/></main>
 return <main><header><div><b onClick={()=>router.push('/')}>LA PULGA</b></div><button className="profileButton" onClick={()=>router.push('/profile')}>👤</button></header><div className="content"><button className="back" onClick={()=>router.push('/profile')}>‹ Profile</button><div className="employeeAdminTitle"><h1>Manage Employees</h1><button className="primary employeeAddButton" onClick={()=>{setForm(blank);setAdding(true);window.scrollTo(0,0)}}>+ Add Employee</button></div><div className="employeeAdminList">{employees.map(e=><div className="employeeAdminRow" key={e.id} onClick={()=>editEmployee(e)} style={{cursor:'pointer'}}><div className="employeeAdminIdentity"><b>{e.name||e.email||'Unnamed Employee'}</b><small>{e.job_title||'No job title'}</small></div><div className="employeeAdminDetails"><span>{e.app_access==='administrator'?'Administrator':'Employee'}</span><span className={'employeeStatus '+(e.status==='active'?'active':'inactive')}>{e.status==='active'?'Active':'Inactive'}</span>{e.status==='active'&&!e.setup_completed_at&&<button className="employeeInviteButton" disabled={busy} onClick={ev=>{ev.stopPropagation();resend(e)}}>Resend Invite</button>}</div></div>)}</div></div><Style/></main>
}
function Style(){return <style>{'.employeeAdminTitle{display:flex;align-items:center;justify-content:space-between;gap:14px;margin-bottom:16px}.employeeAdminTitle h1{margin-bottom:0}.employeeAddButton{width:auto;white-space:nowrap}.employeeAdminList{background:#fff;border:1px solid #ddd;border-radius:14px;overflow:hidden}.employeeAdminRow{padding:16px;display:flex;align-items:center;justify-content:space-between;gap:18px;border-bottom:1px solid #eee}.employeeAdminRow:last-child{border-bottom:0}.employeeAdminIdentity b,.employeeAdminIdentity small{display:block}.employeeAdminIdentity small{color:#777;margin-top:5px}.employeeAdminDetails{display:flex;align-items:center;gap:10px;font-size:13px;white-space:nowrap}.employeeStatus{padding:5px 8px;border-radius:999px;font-weight:700;background:#eee}.employeeStatus.active{background:#e8f5eb}.employeeInviteButton{border:1px solid #bbb;background:#fff;border-radius:8px;padding:6px 9px;font-size:12px;cursor:pointer}.employeeInviteButton:disabled{opacity:.5}.employeeStatus.inactive{background:#f1f1f1;color:#777}.employeeForm{display:grid;gap:15px;max-width:560px}.employeeForm label{font-size:13px;font-weight:650;color:#555}.employeeForm input,.employeeForm select{display:block;width:100%;margin-top:6px;padding:13px;border:1px solid #ccc;border-radius:10px;background:#fff;color:#20201f}.employeeForm .primary{margin-top:5px}@media(max-width:560px){.employeeAdminTitle{align-items:flex-start;flex-direction:column}.employeeAddButton{width:100%}.employeeAdminRow{align-items:flex-start;flex-direction:column;gap:10px}.employeeAdminDetails{width:100%;justify-content:space-between}}'}</style>}
