'use client'
import {useEffect,useState} from 'react'
import {useRouter} from 'next/navigation'
import {createClient} from '../../../lib/supabase'
const supabase=createClient()
export default function EmployeesPage(){
 const router=useRouter(),[employees,setEmployees]=useState([]),[loading,setLoading]=useState(true)
 useEffect(()=>{(async()=>{const{data:{user}}=await supabase.auth.getUser();if(!user){router.replace('/');return}const{data:me}=await supabase.from('employees').select('app_access').eq('id',user.id).single();if(me?.app_access!=='administrator'){router.replace('/profile');return}const{data,error}=await supabase.from('employees').select('id,name,job_title,app_access,status,email').order('name');if(error){alert(error.message);return}setEmployees(data||[]);setLoading(false)})()},[router])
 if(loading)return <main className="center">Loading Employees…</main>
 return <main><header><div><b onClick={()=>router.push('/')}>LA PULGA</b></div><button className="profileButton" onClick={()=>router.push('/profile')}>👤</button></header><div className="content"><button className="back" onClick={()=>router.push('/profile')}>‹ Profile</button><div className="employeeAdminTitle"><h1>Manage Employees</h1><button className="primary employeeAddButton" onClick={()=>alert('Add Employee is next.')}>+ Add Employee</button></div><div className="employeeAdminList">{employees.map(e=><div className="employeeAdminRow" key={e.id}><div className="employeeAdminIdentity"><b>{e.name||e.email||'Unnamed Employee'}</b><small>{e.job_title||'No job title'}</small></div><div className="employeeAdminDetails"><span>{e.app_access==='administrator'?'Administrator':'Employee'}</span><span className={'employeeStatus '+(e.status==='active'?'active':'inactive')}>{e.status==='active'?'Active':'Inactive'}</span></div></div>)}</div>{!employees.length&&<p className="emptyState">No employees found.</p>}</div><style>{'.employeeAdminTitle{display:flex;align-items:center;justify-content:space-between;gap:14px;margin-bottom:16px}.employeeAdminTitle h1{margin-bottom:0}.employeeAddButton{width:auto;white-space:nowrap}.employeeAdminList{background:#fff;border:1px solid #ddd;border-radius:14px;overflow:hidden}.employeeAdminRow{padding:16px;display:flex;align-items:center;justify-content:space-between;gap:18px;border-bottom:1px solid #eee}.employeeAdminRow:last-child{border-bottom:0}.employeeAdminIdentity{min-width:0}.employeeAdminIdentity b,.employeeAdminIdentity small{display:block}.employeeAdminIdentity small{color:#777;margin-top:5px}.employeeAdminDetails{display:flex;align-items:center;gap:10px;font-size:13px;white-space:nowrap}.employeeStatus{padding:5px 8px;border-radius:999px;font-weight:700;background:#eee}.employeeStatus.active{background:#e8f5eb}.employeeStatus.inactive{background:#f1f1f1;color:#777}@media(max-width:560px){.employeeAdminTitle{align-items:flex-start;flex-direction:column}.employeeAddButton{width:100%}.employeeAdminRow{align-items:flex-start;flex-direction:column;gap:10px}.employeeAdminDetails{width:100%;justify-content:space-between}}'}</style></main>
}